import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Header from './_components/Header';
import Footer from './_components/Footer';
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import MySessionProvider from "./_providers/MySessionProvider";
import CartContextProvider from "./_context/CartContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "FreshCart",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body className="min-h-screen flex flex-col">

        <MySessionProvider>
          <CartContextProvider>
            <Header />
            <Navbar />
            <Toaster />
            <main className="flex-1">
              {children}
            </main>

            <Footer />
          </CartContextProvider>
        </MySessionProvider>

      </body>
    </html>
  );
}
